---
- name: Configure office router/AP with tailscale
  hosts: access_points
  become: false
  gather_facts: false
  tasks:
    - name: Include office AP core component taskfile
      ansible.builtin.import_tasks: tasks/router_office_ap_core.yml
    - name: Include office AP tailscale component taskfile
      ansible.builtin.import_tasks: tasks/router_office_ap_tailscale.yml
