---
- name: Configure garage router tailscale profile (exit node)
  hosts: gateway
  become: false
  gather_facts: false

  vars_files:
    - ../../group_vars/all/network.yml
    - ../../group_vars/all/vault.yml

  vars:
    tailscale_hostname: "router-garage"
    tailscale_advertise_exit_node: true

  roles:
    - role: tailscale_openwrt
