---
- name: Configure garage router WireGuard policy-routing profile
  hosts: gateway
  become: false
  gather_facts: false

  vars_files:
    - ../../group_vars/all/network.yml
    - ../../group_vars/all/vault.yml

  roles:
    - role: wireguard_policy_openwrt
