---
- name: Apply gateway-router policy and validation tasks
  ansible.builtin.import_tasks: policy_and_validation.yaml

- name: Apply gateway-router core network tasks
  ansible.builtin.import_tasks: core_network.yaml

- name: Apply gateway-router test-mode verification tasks
  ansible.builtin.import_tasks: test_mode_checks.yaml

- name: Apply gateway-router radio policy tasks
  ansible.builtin.import_tasks: radio_policy.yaml
