$ANSIBLE_VAULT;1.1;AES256
35613134383664343961333261643939333230303937386363393565343632356362323433363631
3734363264326464366330393663373035636430393033310a333663656662653865313361393565
66616634333332306131316636336261616464613239306662336162363662643263386235366139
3463343432666263310a666137333461376633663132646265613731613234346639393937323639
39633230643961643338326237333537373532623363643662653035393964666432353366356531
30643532333137653966633365633666663935323638613736613339646366363239343832306466
32363763393064316334386665653961353739633033356236336161663538663630663630323239
33613963373336306136366664346436646333323238643064346337666630366334323262373062
64386231306335663238326237353934353037623564623633643031396666666533373439366334
33363165626461363462313730316366366238663032333537643938316166633563386363656363
64386663306339653430613761383930613939363435346637303230316535343539306137336435
64396132316231633339626232336161653837656631383861353662626430363031346235653532
61313061396230343266333838376435366265353739383565323536383236643763656439623731
31323834316565343961373538613262636332383438303532336231626161623133336232663761
62313434373038613036363363346465363266353930346637646365323861616134373333386436
64653362343236373830366330623732303964396264623734663930633736366437643533313332
66306337373462643361313030393063306534306638313765343765633465386461373430626631
32623865356566346665323664323933343164363638656664343339346162646130663931623939
30333635643462333562363736396637663136363336333632343335353830386338333363363165
65613335353465623739353135373462363730396530626661306338303562303061356233326561
3536
