$ANSIBLE_VAULT;1.1;AES256
65623763386364383533343732393335653833393963383162653162636135343536316239643164
3036353733356535373233343233383534313733666666300a383765626231366331356538323933
35623762386135333830616531623063336365666566373064623237333030653935653134356335
3032373436306239360a613962386633353533376561326663646163326439326130643832363463
63303439333766333933363638333131343837336535316465373361653932323038366532623932
33313362323036373066343364393064323331363465386431346439653736623566373132353034
39323264316366343064616261633934393966366530316262313464666665656665363332323363
33303835643831393162613331363866353634643162653139313932303537396539656565643130
34313161303530333161366533623533343234353034373032353863306436663365623636656234
37323131626164633238393033383838323463313835326333636630663632343564643263613865
65386436646335616531306633663737376463346434633862326637663732323635623431346335
39313165376439653165373063663835386337326339643034346464366165383062363737313662
39363137346630373737343837643132363362363966323736326638313633343837633335363163
66626238326464343263633236306536313266343738363738633938623231373464343731623433
33316462326262623362303835656433653032353362626464656630633438656161373062623165
61646662396163303839
