$ANSIBLE_VAULT;1.1;AES256
36636665323062613030356232366563326136306335353633336333303132333933666261663836
6661326339346564363965626439333137383236663932340a313165646135376438323334393034
37343830626132633035353034373063363861373734303834353563663532386638623534346334
3662306666383263610a663439356237393335626630656462643265643230313863666266623563
63646639316632353635643530326164303139386531333462366439356230663366363838323865
31353338326635326464663931633332616463666337313865316335343935373936656639666139
35353332363839613832323761373437353437633830613566666365613331643765353130633237
64313464633465306362633036643465663366613435346134346566633963333637663730323861
32353264306337623734336334346534333136643135353833613339393134316531366562613130
31333836353234343031623136653465366161663538313961653939316134346434306462346130
65343031393032353838646563656462633336366365623365366334653263306562366235386461
31373136646438623762663136663530623535363830303234626538626637633632623361363631
33396361363230653531336335313964353137343862613764643831623463373830313131323132
31393661356534666362663039663831346436623432376264623439386366393436656566663433
38346162616431626361643339316237656432386366346435663236626133643534363332653864
30383430643934396362353865613233663665623831353735613035313634643032396632383039
62336264323665316266633936636334313664343164643539376462353632353937313534646261
36353535393066303738333466616261343466623064323232636636633433383066383830383935
66636662303937356238316431643539643161656334656630363233626664343032306665383262
65613236303639626635613034613464613730363163303735376135393665373435666266313634
36613362313330383632353739336331373132613935393035373538386166323966303439303066
39643434356538653138333265643361316162373531653531383437336566353764303631636638
33303637313664326131376566363130646439333033356139656535613330303830393836646631
38636562303165383066313635383363663033633565366636616335343562366433336565313463
38393364376138353330643264393833313235303232613831303536393561333634396135376233
62346166666665643162396534323139633331626239333035376266343564636535383634373932
35366632636533323135363331343639343338656432666539326239323037333932633635396530
34363930363339376135633664353164386334626337633539376665386338653065623433333433
32626538353033623037353135343239306539333662643263333962323633333164643565373464
65386233666462303936313232393235633263373861386261656438333338363230393334343734
35663434323435643861623231323163333163646639303135393861333164353663653733346339
63643762646362666361356334306465393433333432393434643530376335323230613836636437
31393633386431663639323463303532393831336561396230383531303332373533346366373734
3337663033366533376337333061376332616630303732663262
