# --- Global Settings ---
wifi_country: 'GB'

# --- VLAN Schema ---
vlans:
  - { id: 10, name: 'servers', ip: '10.10.0.1', zone: 'server_zone' }
  - { id: 20, name: 'trusted', ip: '10.20.0.1', zone: 'trusted_zone' }
  - { id: 30, name: 'iot',     ip: '10.30.0.1', zone: 'iot_zone' }
  - { id: 99, name: 'guest',   ip: '10.99.0.1', zone: 'guest_zone' }

# --- WiFi Configuration ---
ssids:
  - name: 'trusted'
    ssid: 'meerkat-manor'
    vlan_id: 20
    key: 'FamilyPass2026'
    device: 'radio1'
    encryption: 'sae'
  - name: 'servers'
    ssid: 'meerkat-servers'
    vlan_id: 10
    key: 'AdminAccessOnly'
    device: 'radio1'
    encryption: 'psk2'
  - name: 'iot'
    ssid: 'meerkat-iot'
    vlan_id: 30
    key: 'SmartHomeDevices'
    device: 'radio0'
    encryption: 'psk2'
  - name: 'guest_2g'
    ssid: 'meerkat-guest'
    vlan_id: 99
    key: 'VisitorPass'
    device: 'radio0'
    encryption: 'psk-mixed'
    isolate: '1'
  - name: 'guest_5g'
    ssid: 'meerkat-guest'
    vlan_id: 99
    key: 'VisitorPass'
    device: 'radio1'
    encryption: 'psk-mixed'
    isolate: '1'

forwarding_rules:
  - { src: 'trusted_zone', dest: 'server_zone' }
  - { src: 'trusted_zone', dest: 'wan' }
  - { src: 'server_zone',  dest: 'wan' }
  - { src: 'iot_zone',     dest: 'wan' }
  - { src: 'guest_zone',   dest: 'wan' }
