# Secrets only. Encrypt this file before committing:
# ansible-vault encrypt ansible-meerkat/group_vars/all/vault.yml

vault_wifi_key_manor: 'FamilyPass2026'
vault_wifi_key_iot: 'SmartHomeDevices'
vault_wifi_key_guest: 'VisitorPass'
