---
- name: Configure AP-repeater baseline
  hosts: access_points
  become: false
  gather_facts: false
  vars_files:
    - ../inventory/network.yaml
    - ../inventory/vault.yaml
  roles:
    - ap_repeater
